// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRrRh6nKsJkyOlJ2dxRg8gClkk2kwAAt8',
    appId: '1:517083564684:web:89a15459dec208650cc9a9',
    messagingSenderId: '517083564684',
    projectId: 'ourschat-fe5fb',
    authDomain: 'ourschat-fe5fb.firebaseapp.com',
    storageBucket: 'ourschat-fe5fb.appspot.com',
    measurementId: 'G-Q4ERL68W02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEQQ4Wp2OrJnesLeITPgcU7RFFAEoBkaY',
    appId: '1:517083564684:android:9e5becd0c3b2a81c0cc9a9',
    messagingSenderId: '517083564684',
    projectId: 'ourschat-fe5fb',
    storageBucket: 'ourschat-fe5fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1gWFDgkX2EqMF7zRXtcX-Z3lDXXK3O28',
    appId: '1:517083564684:ios:8aeb91580872c7640cc9a9',
    messagingSenderId: '517083564684',
    projectId: 'ourschat-fe5fb',
    storageBucket: 'ourschat-fe5fb.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1gWFDgkX2EqMF7zRXtcX-Z3lDXXK3O28',
    appId: '1:517083564684:ios:fe5db80b3eed7bb20cc9a9',
    messagingSenderId: '517083564684',
    projectId: 'ourschat-fe5fb',
    storageBucket: 'ourschat-fe5fb.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
